# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: triton_bot_communication.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    2,
    '',
    'triton_bot_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_simulation_robot_control_pb2 as ssl__simulation__robot__control__pb2
import messages_robocup_ssl_detection_pb2 as messages__robocup__ssl__detection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etriton_bot_communication.proto\x12\x0cproto.triton\x1a\"ssl_simulation_robot_control.proto\x1a$messages_robocup_ssl_detection.proto\"\x81\x01\n\x10TritonBotMessage\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x30\n\x06vision\x18\x02 \x01(\x0b\x32 .proto.vision.SSL_DetectionRobot\x12/\n\x07\x63ommand\x18\x03 \x01(\x0b\x32\x1e.proto.simulation.RobotCommandb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'triton_bot_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRITONBOTMESSAGE']._serialized_start=123
  _globals['_TRITONBOTMESSAGE']._serialized_end=252
# @@protoc_insertion_point(module_scope)
