/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_TRITON_TRITON_BOT_COMMUNICATION_PB_H_INCLUDED
#define PB_PROTO_TRITON_TRITON_BOT_COMMUNICATION_PB_H_INCLUDED
#include <pb.h>
#include "ssl_simulation_robot_control.pb.h"
#include "messages_robocup_ssl_detection.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _proto_triton_TritonBotMessage {
    int32_t id;
    bool has_vision;
    proto_vision_SSL_DetectionRobot vision;
    bool has_command;
    proto_simulation_RobotCommand command;
} proto_triton_TritonBotMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define proto_triton_TritonBotMessage_init_default {0, false, proto_vision_SSL_DetectionRobot_init_default, false, proto_simulation_RobotCommand_init_default}
#define proto_triton_TritonBotMessage_init_zero  {0, false, proto_vision_SSL_DetectionRobot_init_zero, false, proto_simulation_RobotCommand_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define proto_triton_TritonBotMessage_id_tag     1
#define proto_triton_TritonBotMessage_vision_tag 2
#define proto_triton_TritonBotMessage_command_tag 3

/* Struct field encoding specification for nanopb */
#define proto_triton_TritonBotMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vision,            2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command,           3)
#define proto_triton_TritonBotMessage_CALLBACK NULL
#define proto_triton_TritonBotMessage_DEFAULT NULL
#define proto_triton_TritonBotMessage_vision_MSGTYPE proto_vision_SSL_DetectionRobot
#define proto_triton_TritonBotMessage_command_MSGTYPE proto_simulation_RobotCommand

extern const pb_msgdesc_t proto_triton_TritonBotMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define proto_triton_TritonBotMessage_fields &proto_triton_TritonBotMessage_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_TRITON_TRITON_BOT_COMMUNICATION_PB_H_MAX_SIZE proto_triton_TritonBotMessage_size
#define proto_triton_TritonBotMessage_size       101

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
