/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "triton_bot_communication.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(proto_triton_TritonBotMessage, proto_triton_TritonBotMessage, AUTO)



