/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "ssl_simulation_robot_control.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(proto_simulation_RobotCommand, proto_simulation_RobotCommand, AUTO)


PB_BIND(proto_simulation_RobotMoveCommand, proto_simulation_RobotMoveCommand, AUTO)


PB_BIND(proto_simulation_MoveWheelVelocity, proto_simulation_MoveWheelVelocity, AUTO)


PB_BIND(proto_simulation_MoveLocalVelocity, proto_simulation_MoveLocalVelocity, AUTO)


PB_BIND(proto_simulation_MoveGlobalVelocity, proto_simulation_MoveGlobalVelocity, AUTO)


PB_BIND(proto_simulation_RobotControl, proto_simulation_RobotControl, AUTO)



