/* USER CODE BEGIN Header */
/**
 ******************************************************************************
 * @file           : main.c
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
/* USER CODE BEGIN Includes */
#include "main.h"
#include "can.h"
#include "dma.h"
#include "tim.h"
#include "usart.h"
#include "gpio.h"
#include "PID.h"
#include <math.h>
#include <string.h>
#include <stdbool.h>

// External UART handle (defined in usart.c, generated by CubeMX)
extern UART_HandleTypeDef huart4;
/* USER CODE END Includes */

/* Private typedef -----------------------------------------------------------*/
/* USER CODE BEGIN PTD */
typedef struct {
	uint32_t magic;
	uint32_t version;
	uint32_t active_pair;
	uint32_t legacy_pair;
	uint32_t legacy_enabled;
	uint32_t checksum;
} HeaderStorageRecord;
/* USER CODE END PTD */

/* Private define ------------------------------------------------------------*/
/* USER CODE BEGIN PD */
#define UART_TX_BUFFER_SIZE 12  // set to the size we want to limit send messages to
#define DEFAULT_HEADER_BYTE_1 0xCA
#define DEFAULT_HEADER_BYTE_2 0xFE
#define LEGACY_HEADER_BYTE_1 0xCA
#define LEGACY_HEADER_BYTE_2 0xFE
#define FRAME_TYPE_DRIVE_COMMAND 0x01
#define FRAME_TYPE_PID_UPDATE    0x02
#define FRAME_TYPE_HEADER_CONFIG 0x03
#define UART_DRIVE_PAYLOAD_SIZE 9
#define UART_PID_PAYLOAD_SIZE 13
#define UART_CONFIG_PAYLOAD_SIZE 3
#define UART_RX_BUFFER_SIZE UART_PID_PAYLOAD_SIZE
#define HEADER_CHECKSUM_SEED 0xA5
#define HEADER_PERSIST_MAGIC 0x48445231u
#define TELEMETRY_HEADER_BYTE_1 0xFE
#define TELEMETRY_HEADER_BYTE_2 0xED
#define TELEMETRY_INTERVAL_MS 50
#define TELEMETRY_WHEEL_FIELDS 3
#define TELEMETRY_WHEEL_STRIDE (TELEMETRY_WHEEL_FIELDS * 2)
#define TELEMETRY_WHEEL_COUNT 4
#define TELEMETRY_FRAME_SIZE (2 + 4 + (TELEMETRY_WHEEL_COUNT * TELEMETRY_WHEEL_STRIDE) + 2)
#define DRIBBLE_ON 0x01
#define REDUCTION_RATIO 36.0
#define RPM_TO_RADS 0.10472
#define HEADER_STORAGE_PTR ((HeaderStorageRecord *)BKPSRAM_BASE)
#define HEADER_STORAGE_VERSION 1u
#define HEADER_LEGACY_GRACE_MS 5000u

/* USER CODE END PD */

/* Private macro -------------------------------------------------------------*/
/* USER CODE BEGIN PM */

/* USER CODE END PM */

/* Private variables ---------------------------------------------------------*/
/* USER CODE BEGIN PV */

// CAN variables
CAN_TxHeaderTypeDef canTxHeader;  // For motors 1-4
CAN_TxHeaderTypeDef canTxHeader2; // For motors 5-8

CAN_RxHeaderTypeDef canRxHeader;
uint32_t canTxMailbox;
uint8_t CAN_TxData[8];
uint8_t CAN2_TxData[8];

uint8_t CAN_RxData[8];

// PID feedback variables
volatile uint8_t motor_idx;
volatile uint16_t angle_data[4];
volatile float speed_data[4];
volatile float torque_current_data[4];
volatile float targetSpeeds[4];
volatile int dribble_speed;
PID_TypeDef motor_pid[4];

/*volatile float Kp1 = 0.503;
volatile float Ki1 = 0.005;
volatile float Kd1 = 0.00;
volatile float Kp2 = 0.3;
volatile float Ki2 = 0.0;
volatile float Kd2 = 0.00;
volatile float Kp3 = 0.273;
volatile float Ki3 = 0.0;
volatile float Kd3 = 0.00;
volatile float Kp4 = 0.403;
volatile float Ki4 = 0.0;
volatile float Kd4 = 0.00;*/

volatile float Kp1 = 100.0f;  // front-right
volatile float Ki1 = 0.0f;
volatile float Kd1 = 0.0f;
volatile float Kp2 = 100.0f;  // back-right
volatile float Ki2 = 0.0f;
volatile float Kd2 = 0.0f;
volatile float Kp3 = 100.0f;  // back-left
volatile float Ki3 = 0.0f;
volatile float Kd3 = 0.0f;
volatile float Kp4 = 100.0f;  // front-left
volatile float Ki4 = 0.0f;
volatile float Kd4 = 0.0f;

// UART setup
uint8_t uart_rx_buffer[UART_RX_BUFFER_SIZE];
uint8_t active_header_byte_1 = DEFAULT_HEADER_BYTE_1;
uint8_t active_header_byte_2 = DEFAULT_HEADER_BYTE_2;
uint8_t legacy_header_byte_1 = LEGACY_HEADER_BYTE_1;
uint8_t legacy_header_byte_2 = LEGACY_HEADER_BYTE_2;
uint8_t uart_tx_buffer[UART_TX_BUFFER_SIZE];
uint8_t telemetry_buffer[TELEMETRY_FRAME_SIZE];

volatile uint8_t rx_byte = 0;
volatile uint8_t expected_header_byte_2 = DEFAULT_HEADER_BYTE_2;
volatile bool header_candidate_is_legacy = false;
bool legacy_accept_enabled = false;
uint32_t legacy_accept_deadline = 0;

typedef enum {
	UART_STATE_WAIT_HEADER_1 = 0,
	UART_STATE_WAIT_HEADER_2,
	UART_STATE_WAIT_TYPE,
	UART_STATE_WAIT_PAYLOAD
} UartState;

volatile UartState uart_state = UART_STATE_WAIT_HEADER_1;
volatile uint8_t current_frame_type = 0;
volatile uint16_t expected_payload_length = 0;
uint32_t last_telemetry_ms = 0;

volatile int timeout;  // timeout for safety mechanism to shutoff robot

/* USER CODE END PV */

/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);
/* USER CODE BEGIN PFP */
static void handle_drive_payload(void);
static void handle_pid_payload(void);
static void handle_header_config_payload(void);
static void apply_pid_constants_for_wheel(uint8_t wheel, float kp, float ki, float kd);
static void reset_uart_state_machine(void);
static float bytes_to_float_be(const uint8_t *bytes);
static void send_telemetry_if_due(void);
static void compose_telemetry_frame(void);
static int16_t clamp_to_int16(float value);
static bool is_header_match(uint8_t candidate, uint8_t expected);
static void ensure_backup_domain_access(void);
static void load_persisted_header(void);
static void persist_header_state(uint8_t active_h1, uint8_t active_h2,
		uint8_t legacy_h1, uint8_t legacy_h2, bool legacy_enabled);
static void unpack_header_pair(uint32_t pair, uint8_t *h1, uint8_t *h2);
static uint32_t pack_header_pair(uint8_t h1, uint8_t h2);
static uint32_t calculate_storage_checksum(uint32_t magic, uint32_t version,
		uint32_t active_pair, uint32_t legacy_pair, uint32_t legacy_enabled);
static void maybe_disable_legacy_window(void);
/* USER CODE END PFP */

/* Private user code ---------------------------------------------------------*/
/* USER CODE BEGIN 0 */

/* USER CODE END 0 */

/**
 * @brief  The application entry point.
 * @retval int
 */

int main(void) {
	/* USER CODE BEGIN 1 */
	/* USER CODE END 1 */

	/* MCU Configuration--------------------------------------------------------*/

	/* Reset of all peripherals, Initializes the Flash interface and the Systick. */
	HAL_Init();

	/* USER CODE BEGIN Init */

	/* USER CODE END Init */

	/* Configure the system clock */
	SystemClock_Config();

	/* USER CODE BEGIN SysInit */

	/* USER CODE END SysInit */
	printf("Hello SWV!\r\n");
	/* Initialize all configured peripherals */
	MX_GPIO_Init();
	MX_DMA_Init();
	MX_CAN1_Init();
	MX_TIM1_Init();
	MX_UART4_Init();
	/* USER CODE BEGIN 2 */

	// Motor setup
	HAL_GPIO_TogglePin(MOTOR_PORT, MOTOR1_PIN);
	HAL_GPIO_TogglePin(MOTOR_PORT, MOTOR2_PIN);
	HAL_GPIO_TogglePin(MOTOR_PORT, MOTOR3_PIN);
	HAL_GPIO_TogglePin(MOTOR_PORT, MOTOR4_PIN);
	HAL_GPIO_TogglePin(MOTOR_PORT, MOTOR5_PIN);

	// CAN setup
	canTxHeader.DLC = 8;
	canTxHeader.IDE = CAN_ID_STD;
	canTxHeader.RTR = CAN_RTR_DATA;
	canTxHeader.StdId = 0x200;
	canTxHeader.TransmitGlobalTime = DISABLE;

	canTxHeader2.DLC = 8;
	canTxHeader2.IDE = CAN_ID_STD;
	canTxHeader2.RTR = CAN_RTR_DATA;
	canTxHeader2.StdId = 0x1FF;
	canTxHeader2.TransmitGlobalTime = DISABLE;

	// Dribbler initialization
	dribble_speed = 0;

	// PID Setup
	for (int i = 0; i < 4; ++i) {
		speed_data[i] = 0;
	}
	pid_init(&motor_pid[0], 9999, 1000, 20, 0, Kp1, Ki1, Kd1);
	pid_init(&motor_pid[1], 9999, 1000, 20, 0, Kp2, Ki2, Kd2);
	pid_init(&motor_pid[2], 9999, 1000, 20, 0, Kp3, Ki3, Kd3);
	pid_init(&motor_pid[3], 9999, 1000, 20, 0, Kp4, Ki4, Kd4);

	for (int i = 0; i < 4; ++i) {
		targetSpeeds[i] = 0;
	}

	// Start program with LEDs off
	HAL_GPIO_WritePin(LED_GREEN_PORT, LED_GREEN_PIN, LED_OFF);
	HAL_GPIO_WritePin(LED_RED_PORT, LED_RED_PIN, LED_OFF);

	load_persisted_header();
	HAL_UART_Receive_IT(&huart4, &rx_byte, 1);

	/* USER CODE END 2 */

	/* Infinite loop */
	/* USER CODE BEGIN WHILE */
	while (1) {

		maybe_disable_legacy_window();

		/*if (timeout >= 200) {             // Safety timeout when UART disconnects
			for (int i = 0; i < 4; ++i) {
				targetSpeeds[i] = 0;
			}
		}*/

		 for (int i = 0; i < 4; ++i) {                          // PID control loop
			 motor_pid[i].target = ((float)targetSpeeds[i]) / 100.0f;
			 pid_calculate(&motor_pid[i],speed_data[i]);
		 }

		 setMotorSpeeds((motor_pid[0].output), (motor_pid[1].output), (motor_pid[2].output), (motor_pid[3].output), dribble_speed * 100);
		 send_telemetry_if_due();

		timeout++;
		HAL_Delay(10);
		/* USER CODE END WHILE */

		/* USER CODE BEGIN 3 */
		/* USER CODE END 3 */
	}
}

void HAL_CAN_RxFifo0MsgPendingCallback(CAN_HandleTypeDef *hcan) {
	//HAL_GPIO_TogglePin(LED_GREEN_PORT,LED_GREEN_PIN);
	if (hcan == &hcan1) {
		HAL_CAN_GetRxMessage(&hcan1, CAN_RX_FIFO0, &canRxHeader, CAN_RxData);

		if (canRxHeader.StdId == 0x201)
			motor_idx = 0;
		if (canRxHeader.StdId == 0x202)
			motor_idx = 1;
		if (canRxHeader.StdId == 0x203)
			motor_idx = 2;
		if (canRxHeader.StdId == 0x204)
			motor_idx = 3;

		// angle of the motor (0 - 8191 corresponding with 0 - 360°)
		angle_data[motor_idx] = (uint16_t) (CAN_RxData[0] << 8 | CAN_RxData[1]);

		// speed of the motor in rpm
		int16_t rpm = (int16_t)((CAN_RxData[2] << 8) | CAN_RxData[3]);
		// convert to rad/s
		speed_data[motor_idx] = (rpm / REDUCTION_RATIO) * RPM_TO_RADS;

		// torque current of the motor
		torque_current_data[motor_idx] = (CAN_RxData[4] << 8 | CAN_RxData[5]);
	}
}

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart) {
	if (huart != &huart4) {
		return;
	}

	switch (uart_state) {
	case UART_STATE_WAIT_HEADER_1:
		if (rx_byte == active_header_byte_1) {
			expected_header_byte_2 = active_header_byte_2;
			header_candidate_is_legacy = false;
			uart_state = UART_STATE_WAIT_HEADER_2;
		} else if (legacy_accept_enabled && (rx_byte == legacy_header_byte_1)) {
			expected_header_byte_2 = legacy_header_byte_2;
			header_candidate_is_legacy = true;
			uart_state = UART_STATE_WAIT_HEADER_2;
		}
		HAL_UART_Receive_IT(&huart4, &rx_byte, 1);
		break;
	case UART_STATE_WAIT_HEADER_2:
		if (is_header_match(rx_byte, expected_header_byte_2)) {
			uart_state = UART_STATE_WAIT_TYPE;
		} else if (rx_byte == active_header_byte_1 || (legacy_accept_enabled && rx_byte == legacy_header_byte_1)) {
			expected_header_byte_2 = (rx_byte == active_header_byte_1) ? active_header_byte_2 : legacy_header_byte_2;
			header_candidate_is_legacy = (rx_byte == legacy_header_byte_1);
			uart_state = UART_STATE_WAIT_HEADER_2;
		} else {
			uart_state = UART_STATE_WAIT_HEADER_1;
		}
		HAL_UART_Receive_IT(&huart4, &rx_byte, 1);
		break;
	case UART_STATE_WAIT_TYPE:
		current_frame_type = rx_byte;
		switch (current_frame_type) {
		case FRAME_TYPE_DRIVE_COMMAND:
			expected_payload_length = UART_DRIVE_PAYLOAD_SIZE;
			break;
		case FRAME_TYPE_PID_UPDATE:
			expected_payload_length = UART_PID_PAYLOAD_SIZE;
			break;
		case FRAME_TYPE_HEADER_CONFIG:
			expected_payload_length = UART_CONFIG_PAYLOAD_SIZE;
			break;
		default:
			expected_payload_length = 0;
			break;
		}
		if (expected_payload_length > 0) {
			uart_state = UART_STATE_WAIT_PAYLOAD;
			HAL_UART_Receive_IT(&huart4, uart_rx_buffer, expected_payload_length);
		} else {
			reset_uart_state_machine();
		}
		break;
	case UART_STATE_WAIT_PAYLOAD:
		if (current_frame_type == FRAME_TYPE_DRIVE_COMMAND) {
			handle_drive_payload();
		} else if (current_frame_type == FRAME_TYPE_PID_UPDATE) {
			handle_pid_payload();
		} else if (current_frame_type == FRAME_TYPE_HEADER_CONFIG) {
			handle_header_config_payload();
		}
		reset_uart_state_machine();
		break;
	default:
		reset_uart_state_machine();
		break;
	}
}

/**
 * @brief System Clock Configuration
 * @retval None
 */
void SystemClock_Config(void) {
	RCC_OscInitTypeDef RCC_OscInitStruct = { 0 };
	RCC_ClkInitTypeDef RCC_ClkInitStruct = { 0 };

	/** Configure the main internal regulator output voltage
	 */
	__HAL_RCC_PWR_CLK_ENABLE();
	__HAL_PWR_VOLTAGESCALING_CONFIG(PWR_REGULATOR_VOLTAGE_SCALE1);

	/** Initializes the RCC Oscillators according to the specified parameters
	 * in the RCC_OscInitTypeDef structure.
	 */
	RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSE;
	RCC_OscInitStruct.HSEState = RCC_HSE_ON;
	RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
	RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSE;
	RCC_OscInitStruct.PLL.PLLM = 6;
	RCC_OscInitStruct.PLL.PLLN = 168;
	RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
	RCC_OscInitStruct.PLL.PLLQ = 4;
	if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK) {
		Error_Handler();
	}

	/** Initializes the CPU, AHB and APB buses clocks
	 */
	RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK
			| RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2;
	RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
	RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
	RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV4;
	RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV2;

	if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_5) != HAL_OK) {
		Error_Handler();
	}
}

/* USER CODE BEGIN 4 */
void setMotorSpeeds(int16_t ms1, int16_t ms2, int16_t ms3, int16_t ms4, int16_t msg5) {
	uint8_t h1 = ms1 >> 8;
	uint8_t l1 = ms1;
	uint8_t h2 = ms2 >> 8;
	uint8_t l2 = ms2;
	uint8_t h3 = ms3 >> 8;
	uint8_t l3 = ms3;
	uint8_t h4 = ms4 >> 8;
	uint8_t l4 = ms4;
	uint8_t h5 = msg5 >> 8;
	uint8_t l5 = msg5;
	runMotors(h1, l1, h2, l2, h3, l3, h4, l4, h5, l5);
}

void runMotors(unsigned char motorOneHigh, unsigned char motorOneLow,
		unsigned char motorTwoHigh, unsigned char motorTwoLow,
		unsigned char motorThreeHigh, unsigned char motorThreeLow,
		unsigned char motorFourHigh, unsigned char motorFourLow,
		unsigned char motorFiveHigh, unsigned char motorFiveLow) {

	//speed can be 16 bits, split into high and low bytes
	CAN_TxData[0] = motorOneHigh;      //high byte for speed, shifted 8 because only buffer is only 8 bits
	CAN_TxData[1] = motorOneLow;       //low bytes for speed
	CAN_TxData[2] = motorTwoHigh;
	CAN_TxData[3] = motorTwoLow;
	CAN_TxData[4] = motorThreeHigh;
	CAN_TxData[5] = motorThreeLow;
	CAN_TxData[6] = motorFourHigh;
	CAN_TxData[7] = motorFourLow;

	CAN2_TxData[0] = motorFiveHigh;
	CAN2_TxData[1] = motorFiveLow;

	HAL_CAN_AddTxMessage(&hcan1, &canTxHeader, CAN_TxData, &canTxMailbox);
	HAL_CAN_AddTxMessage(&hcan1, &canTxHeader2, CAN2_TxData, &canTxMailbox);
}

static void handle_drive_payload(void) {
	timeout = 0;
	for (int i = 0; i < 4; ++i) {
		const int index = i * 2;
		int16_t raw_value = (int16_t) ((uart_rx_buffer[index] << 8) | uart_rx_buffer[index + 1]);
		targetSpeeds[i] = raw_value;
	}
	dribble_speed = (int8_t) uart_rx_buffer[8];
	memset(uart_rx_buffer, 0, UART_RX_BUFFER_SIZE);
	HAL_GPIO_TogglePin(LED_GREEN_PORT, LED_GREEN_PIN);
}

static void apply_pid_constants_for_wheel(uint8_t wheel, float kp, float ki, float kd) {
	pid_set_constants(&motor_pid[wheel], kp, ki, kd);
	motor_pid[wheel].integral = 0.0f;
	motor_pid[wheel].error = 0.0f;
	motor_pid[wheel].last_error = 0.0f;
	motor_pid[wheel].output = 0.0f;
	switch (wheel) {
	case 0:
		Kp1 = kp;
		Ki1 = ki;
		Kd1 = kd;
		break;
	case 1:
		Kp2 = kp;
		Ki2 = ki;
		Kd2 = kd;
		break;
	case 2:
		Kp3 = kp;
		Ki3 = ki;
		Kd3 = kd;
		break;
	case 3:
		Kp4 = kp;
		Ki4 = ki;
		Kd4 = kd;
		break;
	default:
		break;
	}
}

static void handle_pid_payload(void) {
	if (expected_payload_length != UART_PID_PAYLOAD_SIZE) {
		return;
	}
	uint8_t wheel = uart_rx_buffer[0];
	float kp = bytes_to_float_be(&uart_rx_buffer[1]);
	float ki = bytes_to_float_be(&uart_rx_buffer[5]);
	float kd = bytes_to_float_be(&uart_rx_buffer[9]);
	if (wheel < 4) {
		apply_pid_constants_for_wheel(wheel, kp, ki, kd);
	} else if (wheel == 0xFF) {
		for (uint8_t i = 0; i < 4; ++i) {
			apply_pid_constants_for_wheel(i, kp, ki, kd);
		}
	}
}

static void handle_header_config_payload(void) {
	if (expected_payload_length != UART_CONFIG_PAYLOAD_SIZE) {
		return;
	}
	uint8_t new_header_1 = uart_rx_buffer[0];
	uint8_t new_header_2 = uart_rx_buffer[1];
	uint8_t checksum = uart_rx_buffer[2];
	uint8_t expected_checksum = HEADER_CHECKSUM_SEED ^ new_header_1 ^ new_header_2;
	if (checksum != expected_checksum) {
		return;
	}
	uint8_t prev_header_1 = active_header_byte_1;
	uint8_t prev_header_2 = active_header_byte_2;
	active_header_byte_1 = new_header_1;
	active_header_byte_2 = new_header_2;
	legacy_header_byte_1 = prev_header_1;
	legacy_header_byte_2 = prev_header_2;
	legacy_accept_enabled = true;
	legacy_accept_deadline = HAL_GetTick() + HEADER_LEGACY_GRACE_MS;
	persist_header_state(active_header_byte_1, active_header_byte_2,
		legacy_header_byte_1, legacy_header_byte_2, legacy_accept_enabled);
}

static void reset_uart_state_machine(void) {
	uart_state = UART_STATE_WAIT_HEADER_1;
	current_frame_type = 0;
	expected_payload_length = 0;
	expected_header_byte_2 = active_header_byte_2;
	header_candidate_is_legacy = false;
	HAL_UART_Receive_IT(&huart4, &rx_byte, 1);
}

static float bytes_to_float_be(const uint8_t *bytes) {
	uint32_t value = ((uint32_t) bytes[0] << 24) |
			((uint32_t) bytes[1] << 16) |
			((uint32_t) bytes[2] << 8) |
			((uint32_t) bytes[3]);
	float result;
	memcpy(&result, &value, sizeof(float));
	return result;
}

static void send_telemetry_if_due(void) {
	uint32_t now = HAL_GetTick();
	if ((now - last_telemetry_ms) < TELEMETRY_INTERVAL_MS) {
		return;
	}
	last_telemetry_ms = now;
	compose_telemetry_frame();
	HAL_UART_Transmit(&huart4, telemetry_buffer, TELEMETRY_FRAME_SIZE, HAL_MAX_DELAY);
}

static int16_t clamp_to_int16(float value) {
	if (value > INT16_MAX) {
		return INT16_MAX;
	}
	if (value < INT16_MIN) {
		return INT16_MIN;
	}
	return (int16_t) value;
}

static bool is_header_match(uint8_t candidate, uint8_t expected) {
	return candidate == expected;
}

static void ensure_backup_domain_access(void) {
	__HAL_RCC_PWR_CLK_ENABLE();
	HAL_PWR_EnableBkUpAccess();
	__HAL_RCC_BKPSRAM_CLK_ENABLE();
}

static void load_persisted_header(void) {
	ensure_backup_domain_access();
	const HeaderStorageRecord *stored = HEADER_STORAGE_PTR;
	uint32_t active_pair = pack_header_pair(DEFAULT_HEADER_BYTE_1,
			DEFAULT_HEADER_BYTE_2);
	uint32_t legacy_pair = pack_header_pair(LEGACY_HEADER_BYTE_1,
			LEGACY_HEADER_BYTE_2);
	uint32_t legacy_flag = 0;
	bool valid = false;
	uint32_t expected_checksum = calculate_storage_checksum(HEADER_PERSIST_MAGIC,
			HEADER_STORAGE_VERSION, stored->active_pair, stored->legacy_pair,
			stored->legacy_enabled);
	if ((stored->magic == HEADER_PERSIST_MAGIC)
			&& (stored->version == HEADER_STORAGE_VERSION)
			&& (stored->checksum == expected_checksum)) {
		active_pair = stored->active_pair;
		legacy_pair = stored->legacy_pair;
		legacy_flag = stored->legacy_enabled;
		valid = true;
	}
	uint8_t active_h1;
	uint8_t active_h2;
	uint8_t legacy_h1;
	uint8_t legacy_h2;
	unpack_header_pair(active_pair, &active_h1, &active_h2);
	unpack_header_pair(legacy_pair, &legacy_h1, &legacy_h2);
	active_header_byte_1 = active_h1;
	active_header_byte_2 = active_h2;
	legacy_header_byte_1 = legacy_h1;
	legacy_header_byte_2 = legacy_h2;
	legacy_accept_enabled = (legacy_flag != 0u);
	if (!valid) {
		persist_header_state(active_header_byte_1, active_header_byte_2,
			legacy_header_byte_1, legacy_header_byte_2, legacy_accept_enabled);
	}
	if (legacy_accept_enabled) {
		legacy_accept_deadline = HAL_GetTick() + HEADER_LEGACY_GRACE_MS;
	} else {
		legacy_accept_deadline = 0;
	}
}

static uint32_t pack_header_pair(uint8_t h1, uint8_t h2) {
	return ((uint32_t) h1 << 8) | h2;
}

static void unpack_header_pair(uint32_t pair, uint8_t *h1, uint8_t *h2) {
	*h1 = (pair >> 8) & 0xFF;
	*h2 = pair & 0xFF;
}

static uint32_t calculate_storage_checksum(uint32_t magic, uint32_t version,
		uint32_t active_pair, uint32_t legacy_pair, uint32_t legacy_enabled) {
	uint32_t checksum = HEADER_CHECKSUM_SEED;
	checksum ^= magic;
	checksum ^= version;
	checksum ^= active_pair;
	checksum ^= legacy_pair;
	checksum ^= legacy_enabled;
	return checksum;
}

static void persist_header_state(uint8_t active_h1, uint8_t active_h2,
		uint8_t legacy_h1, uint8_t legacy_h2, bool legacy_enabled) {
	ensure_backup_domain_access();
	HeaderStorageRecord record;
	record.magic = HEADER_PERSIST_MAGIC;
	record.version = HEADER_STORAGE_VERSION;
	record.active_pair = pack_header_pair(active_h1, active_h2);
	record.legacy_pair = pack_header_pair(legacy_h1, legacy_h2);
	record.legacy_enabled = legacy_enabled ? 1u : 0u;
	record.checksum = calculate_storage_checksum(record.magic,
			record.version, record.active_pair, record.legacy_pair,
			record.legacy_enabled);
	memcpy((void *) HEADER_STORAGE_PTR, &record, sizeof(record));
}

static void maybe_disable_legacy_window(void) {
	if (!legacy_accept_enabled) {
		return;
	}
	uint32_t now = HAL_GetTick();
	if ((int32_t) (now - legacy_accept_deadline) >= 0) {
		legacy_accept_enabled = false;
		legacy_accept_deadline = 0;
		persist_header_state(active_header_byte_1, active_header_byte_2,
			legacy_header_byte_1, legacy_header_byte_2, legacy_accept_enabled);
	}
}

static void compose_telemetry_frame(void) {
	telemetry_buffer[0] = TELEMETRY_HEADER_BYTE_1;
	telemetry_buffer[1] = TELEMETRY_HEADER_BYTE_2;
	uint32_t timestamp = HAL_GetTick();
	telemetry_buffer[2] = (timestamp >> 24) & 0xFF;
	telemetry_buffer[3] = (timestamp >> 16) & 0xFF;
	telemetry_buffer[4] = (timestamp >> 8) & 0xFF;
	telemetry_buffer[5] = (timestamp & 0xFF);
	for (int i = 0; i < TELEMETRY_WHEEL_COUNT; ++i) {
		int base = 6 + (i * TELEMETRY_WHEEL_STRIDE);
		int16_t target = clamp_to_int16(targetSpeeds[i]);
		int16_t actual = clamp_to_int16(speed_data[i] * 100.0f);
		int16_t output = clamp_to_int16(motor_pid[i].output);
		telemetry_buffer[base] = (target >> 8) & 0xFF;
		telemetry_buffer[base + 1] = target & 0xFF;
		telemetry_buffer[base + 2] = (actual >> 8) & 0xFF;
		telemetry_buffer[base + 3] = actual & 0xFF;
		telemetry_buffer[base + 4] = (output >> 8) & 0xFF;
		telemetry_buffer[base + 5] = output & 0xFF;
	}
	int16_t dribble_word = clamp_to_int16(dribble_speed * 100.0f);
	int tail = 6 + (TELEMETRY_WHEEL_COUNT * TELEMETRY_WHEEL_STRIDE);
	telemetry_buffer[tail] = (dribble_word >> 8) & 0xFF;
	telemetry_buffer[tail + 1] = dribble_word & 0xFF;
}

/* USER CODE END 4 */

/**
 * @brief  Period elapsed callback in non blocking mode
 * @note   This function is called  when TIM6 interrupt took place, inside
 * HAL_TIM_IRQHandler(). It makes a direct call to HAL_IncTick() to increment
 * a global variable "uwTick" used as application time base.
 * @param  htim : TIM handle
 * @retval None
 */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim) {
	/* USER CODE BEGIN Callback 0 */

	/* USER CODE END Callback 0 */
	if (htim->Instance == TIM6) {
		HAL_IncTick();
	}
	/* USER CODE BEGIN Callback 1 */

	/* USER CODE END Callback 1 */
}

/**
 * @brief  This function is executed in case of error occurrence.
 * @retval None
 */
void Error_Handler(void) {
	/* USER CODE BEGIN Error_Handler_Debug */
	/* User can add his own implementation to report the HAL error return state */
	__disable_irq();
	while (1) {
	}
	/* USER CODE END Error_Handler_Debug */
}

#ifdef  USE_FULL_ASSERT
/**
  * @brief  Reports the name of the source file and the source line number
  *         where the assert_param error has occurred.
  * @param  file: pointer to the source file name
  * @param  line: assert_param error line source number
  * @retval None
  */
void assert_failed(uint8_t *file, uint32_t line)
{
  /* USER CODE BEGIN 6 */
  /* User can add his own implementation to report the file name and line number,
     ex: printf("Wrong parameters value: file %s on line %d\r\n", file, line) */
  /* USER CODE END 6 */
}
#endif /* USE_FULL_ASSERT */
